version: '3.7'
services:
  django:
    restart: always
    environment:
    - SECRET_KEY
    volumes:
    - ./mrsattachments:/mrsattachments
    - ./log:/app/log
    labels:
    - "io.yourlabs.compose.mkdir=./mrsattachments:1000:1000:0750"
    - "io.yourlabs.compose.mkdir=./log:1000:1000:0750"
    - "io.yourlabs.compose.mkdir=./spooler:1000:1000:0750"
    - "io.yourlabs.compose.mkdir=./spooler/mail:1000:1000:0750"
    - "io.yourlabs.compose.mkdir=./spooler/stat:1000:1000:0750"

  postgres:
    restart: always
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/run:/var/run/postgresql
    - ./dump:/dump
